<?php
if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class T04_armada_model extends CI_Model
{

    public $table = 't04_armada';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json()
    {
        $this->datatables->select('id,merk,tipe,tahun_pembuatan,harga_beli,nomor_polisi,nomor_rangka,nomor_mesin,tanggal_pembelian,tanggal_jatuh_tempo_pajak,tanggal_jatuh_tempo_kir');
        $this->datatables->from('t04_armada');
        //add this line for join
        //$this->datatables->join('table2', 't04_armada.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('t04_armada/read/$1'),'Read')." | ".anchor(site_url('t04_armada/update/$1'),'Update')." | ".anchor(site_url('t04_armada/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id');
        return $this->datatables->generate();
    }

    function json2()
    {
        $columns = array(
            array('db' => 'id', 'dt' => 0, 'formatter' => function($d, $row) {return '';}),
            array('db' => 'merk', 'dt' => 1),
            array('db' => 'tipe', 'dt' => 2),
            array('db' => 'tahun_pembuatan', 'dt' => 3),
            array('db' => 'harga_beli', 'dt' => 4),
            array('db' => 'nomor_polisi', 'dt' => 5),
            array('db' => 'nomor_rangka', 'dt' => 6),
            array('db' => 'nomor_mesin', 'dt' => 7),
            array('db' => 'tanggal_pembelian', 'dt' => 8),
            array('db' => 'tanggal_jatuh_tempo_pajak', 'dt' => 9),
            array('db' => 'tanggal_jatuh_tempo_kir', 'dt' => 10),
            array('db' => 'id', 'dt' => 11, 'formatter' => function($d, $row) {
                return '
                    <a href="'.site_url().'t04_armada/read/'.$d.'">Read</a> |
                    <a href="'.site_url().'t04_armada/update/'.$d.'">Update</a> |
                    <a href="'.site_url().'t04_armada/delete/'.$d.'" onclick="javascript: return confirm(\'Are you sure ?\')">Delete</a>
                    ';
            }),
        );

        $this->load->database();
        $sql_details = array(
            'user' => $this->db->username,
            'pass' => $this->db->password,
            'db' => $this->db->database,
            'host' => $this->db->hostname,
        );
        return json_encode(SSP::simple($_GET, $sql_details, $this->table, $this->id, $columns));
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL)
    {
        $this->db->like('id', $q);
        $this->db->or_like('merk', $q);
        $this->db->or_like('tipe', $q);
        $this->db->or_like('tahun_pembuatan', $q);
        $this->db->or_like('harga_beli', $q);
        $this->db->or_like('nomor_polisi', $q);
        $this->db->or_like('nomor_rangka', $q);
        $this->db->or_like('nomor_mesin', $q);
        $this->db->or_like('tanggal_pembelian', $q);
        $this->db->or_like('tanggal_jatuh_tempo_pajak', $q);
        $this->db->or_like('tanggal_jatuh_tempo_kir', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL)
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
        $this->db->or_like('merk', $q);
        $this->db->or_like('tipe', $q);
        $this->db->or_like('tahun_pembuatan', $q);
        $this->db->or_like('harga_beli', $q);
        $this->db->or_like('nomor_polisi', $q);
        $this->db->or_like('nomor_rangka', $q);
        $this->db->or_like('nomor_mesin', $q);
        $this->db->or_like('tanggal_pembelian', $q);
        $this->db->or_like('tanggal_jatuh_tempo_pajak', $q);
        $this->db->or_like('tanggal_jatuh_tempo_kir', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file T04_armada_model.php */
/* Location: ./application/models/T04_armada_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2024-02-02 04:00:59 */
/* http://harviacode.com */